flags: {}
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: f15dc42720ddc6c928c15dd34fac01f5548fe872
- location:
    git: https://github.com/plaprade/haskoin-node.git
    commit: 3145b47fe17b6f9109b78d80d351c53ab5c0e2cc
extra-deps:
- SafeSemaphore-0.10.1
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
- esqueleto-2.2.7
resolver: lts-2.15
